apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-schema
spec:
  replicas: 2
  selector:
    matchLabels: { app: bad-schema }
  template:
    metadata:
      labels: { app: bad-schema }
    spec:
      containers:
        - name: c
          image: ghcr.io/stefanprodan/podinfo:6.7.1
